# Generated by Django 3.2 on 2022-09-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skincare.brand', to_field='friendly_name')),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
    ]
