# Generated by Django 3.2 on 2022-09-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['first_letter']},
        ),
    ]
