# Generated by Django 3.2 on 2022-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_alter_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.CharField(max_length=20)),
                ('dry', models.CharField(max_length=20)),
                ('oily', models.CharField(max_length=20)),
                ('combination', models.CharField(max_length=20)),
                ('sensitive', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Skin Type',
            },
        ),
    ]
