# Generated by Django 3.2 on 2023-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_auto_20221222_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincare',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
