# Generated by Django 3.2 on 2022-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_skintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skintype',
            name='combination',
        ),
        migrations.RemoveField(
            model_name='skintype',
            name='dry',
        ),
        migrations.RemoveField(
            model_name='skintype',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='skintype',
            name='oily',
        ),
        migrations.RemoveField(
            model_name='skintype',
            name='sensitive',
        ),
        migrations.AddField(
            model_name='skintype',
            name='skin_type_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skintype',
            name='skin_type_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skintype',
            name='skin_type_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skintype',
            name='skin_type_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skintype',
            name='skin_type_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
